require("plugins.packer")
require("plugins.mason")
require("plugins.nvim-tree")
require("plugins.toggleterm")
require("plugins.aerial")
require("plugins.lspkind")
require("plugins.nvim-cmp")
-- require("plugins.catppuccin")
require("plugins.kanagawa")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.indent-blankline")
